Repository codestates-seb/seb45_main_010, pull requests merged in 2023-09, with the labels that each got.

#14 Fe add sign up design #13
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/모네-수련.jpeg
  client/src/components/Header/Header.tsx
  client/src/index.css
  client/src/pages/GetPassword.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/pages/SignUp.tsx
  client/tailwind.config.js
Labels: FE

#15 Fe add layout
  client/src/App.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Menu/Search.tsx
  client/src/components/Menu/Sidebar.tsx
  client/src/configs/Footer/configs.tsx
  client/src/index.css
Labels: FE

#22 [Feat] add 시큐리티 JWT 로그인 기능
  server/build.gradle
  server/src/main/java/com/codestates/connectInstructor/exception/ExceptionCode.java
  server/src/main/java/com/codestates/connectInstructor/response/ErrorResponse.java
  server/src/main/java/com/codestates/connectInstructor/security/config/SecurityConfiguration.java
  server/src/main/java/com/codestates/connectInstructor/security/dto/LoginDto.java
  server/src/main/java/com/codestates/connectInstructor/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/connectInstructor/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/codestates/connectInstructor/security/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/codestates/connectInstructor/security/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/codestates/connectInstructor/security/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/codestates/connectInstructor/security/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/codestates/connectInstructor/security/jwt/JwtTokenizer.java
  server/src/main/java/com/codestates/connectInstructor/security/member/Member.java
  server/src/main/java/com/codestates/connectInstructor/security/userdetails/MemberDetailsService.java
  server/src/main/java/com/codestates/connectInstructor/security/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codestates/connectInstructor/security/utils/ErrorResponder.java
  server/src/main/java/com/codestates/connectInstructor/student/entity/Student.java
  server/src/main/java/com/codestates/connectInstructor/student/service/StudentService.java
  server/src/main/java/com/codestates/connectInstructor/teacher/entity/Teacher.java
  server/src/main/java/com/codestates/connectInstructor/teacher/service/TeacherService.java
  server/src/main/resources/application.yml
Labels: BE

#19 Fe add list page
  .DS_Store
  client/src/App.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/components/ListPage/Pagination.tsx
  client/src/components/ListPage/TeacherCard.tsx
  client/src/components/Menu/Sidebar.tsx
  client/src/configs/List/config.tsx
  client/src/index.css
  client/src/pages/ListPage/ListPage.tsx
  client/src/router/root.tsx
  client/tailwind.config.js
Labels: FE

#20 #18 [FEAT]add_signUp_function
  client/data/data1.json
  client/src/pages/GetPassword.tsx
  client/src/pages/Login.tsx
  client/src/pages/SignUp.tsx
  client/tailwind.config.js
Labels: FE

#23 Fe add teacher profile page
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/Image/user-example.png
  client/src/components/Menu/Search.tsx
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/Calendar.tsx
  client/src/components/Profile/ProfileTab/OptionList.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Profile/ProfileTab/ScheduleList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/index.css
  client/src/pages/DetailPage/DetailPage.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/pages/Profile/StudentProfile.tsx
  client/src/router/root.tsx
  client/tailwind.config.js
Labels: FE

#24 Fe add detail page
  client/src/components/Profile/ProfileBody.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/pages/Profile/StudentProfile.tsx
Labels: FE

#31 Fe add redux toolkit
  client/src/components/Counter.tsx
  client/src/hooks/hooks.tsx
  client/src/main.tsx
  client/src/redux/slice/CounterSlice.tsx
  client/src/redux/store.tsx
Labels: FE

#32 Fe add email duplicate
  client/data/data1.json
  client/data1.json
  client/src/pages/Login.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/SignUp/SignUp_MUIform_Error.tsx
Labels: FE

#27 [fix] 화살표 함수로 통일 / tab css 수정
  client/src/components/Profile/ProfileBody.tsx
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/Calendar.tsx
  client/src/components/Profile/ProfileTab/OptionList.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Profile/ProfileTab/ScheduleList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/pages/DetailPage/DetailPage.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/pages/Profile/StudentProfile.tsx
Labels: FE

#30 Fe add profile function
  client/data/data2.json
  client/data2.json
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/Calendar.tsx
  client/src/components/Profile/ProfileTab/OptionList.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Profile/ProfileTab/ScheduleList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/components/Type/User.tsx
  client/src/pages/Profile/Profile.tsx
Labels: FE

#33 [Style] modify 리뷰내용 토대로 스타일 수정
  client/src/App.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/components/ListPage/Pagination.tsx
  client/src/components/ListPage/TeacherCard.tsx
  client/src/components/Menu/Search.tsx
  client/src/components/Menu/Sidebar.tsx
  client/src/components/Modal/AlertModal.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/index.css
  client/src/pages/GetPassword.tsx
  client/src/pages/ListPage/ListPage.tsx
  client/tailwind.config.js
Labels: FE

#34 [fix] css(패딩값, 요소너비) / type 명 설정
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/Calendar.tsx
  client/src/components/Profile/ProfileTab/OptionList.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Profile/ProfileTab/ScheduleList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/pages/Profile/StudentProfile.tsx
Labels: FE

#36 #18 Refactor_EmailSignup
  client/data/data1.json
  client/src/pages/SignUp.tsx
Labels: FE

#42 Fe add search password with email account
  client/src/pages/GetPassword.tsx
  client/src/pages/SignUp/SignUp_MUIform_Error.tsx
  data1.json
Labels: FE

#29 [Feat] add 예외처리추가. GlobalExceptionAdvice
  server/src/main/java/com/codestates/connectInstructor/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/connectInstructor/match/controller/MatchController.java
  server/src/main/java/com/codestates/connectInstructor/match/dto/MatchDto.java
  server/src/main/java/com/codestates/connectInstructor/match/entity/Match.java
  server/src/main/java/com/codestates/connectInstructor/match/mapper/MatchMapper.java
  server/src/main/java/com/codestates/connectInstructor/match/repository/MatchRepository.java
  server/src/main/java/com/codestates/connectInstructor/match/service/MatchService.java
  server/src/main/java/com/codestates/connectInstructor/region/controller/RegionController.java
  server/src/main/java/com/codestates/connectInstructor/region/dto/RegionDto.java
  server/src/main/java/com/codestates/connectInstructor/region/entity/Region.java
  server/src/main/java/com/codestates/connectInstructor/region/mapper/RegionMapper.java
  server/src/main/java/com/codestates/connectInstructor/region/repository/RegionRepository.java
  server/src/main/java/com/codestates/connectInstructor/region/service/RegionService.java
  server/src/main/java/com/codestates/connectInstructor/student/controller/StudentController.java
  server/src/main/java/com/codestates/connectInstructor/student/dto/StudentDto.java
  server/src/main/java/com/codestates/connectInstructor/student/entity/Student.java
  server/src/main/java/com/codestates/connectInstructor/subject/controller/SubjectController.java
  server/src/main/java/com/codestates/connectInstructor/subject/dto/SubjectDto.java
  server/src/main/java/com/codestates/connectInstructor/subject/entity/Subject.java
  server/src/main/java/com/codestates/connectInstructor/subject/mapper/SubjectMapper.java
  server/src/main/java/com/codestates/connectInstructor/subject/repository/SubjectRepository.java
  server/src/main/java/com/codestates/connectInstructor/subject/service/SubjectService.java
  server/src/main/java/com/codestates/connectInstructor/teacher/controller/TeacherController.java
  server/src/main/java/com/codestates/connectInstructor/teacher/dto/TeacherDto.java
  server/src/main/java/com/codestates/connectInstructor/teacher/entity/Teacher.java
  server/src/main/java/com/codestates/connectInstructor/teacher/entity/TeacherRegion.java
  server/src/main/java/com/codestates/connectInstructor/teacher/entity/TeacherSubject.java
  server/src/main/java/com/codestates/connectInstructor/utils/UriCreator.java
Labels: BE

#45 Fe add schedule
  client/src/components/Items/OnlineDiv.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/Calendar.tsx
  client/src/components/Profile/ProfileTab/OptionList.tsx
  client/src/components/Profile/ProfileTab/ScheduleList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/redux/slice/PofileSilce.tsx
Labels: FE

#51 Design_Width_Trim_Member
  client/src/pages/GetPassword.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/pages/SignUp.tsx
Labels: enhancement, FE

#52 Fe add profile function
  client/data/data2.json
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/Option.tsx
  client/src/components/Profile/ProfileTab/OptionList.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Profile/ProfileTab/ScheduleList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/components/Types/Types.tsx
  client/src/components/Types/User.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/redux/slice/PofileSilce.tsx
  client/src/redux/slice/RequestSlice.tsx
  client/src/redux/store.tsx
  client/src/redux/thunk/Thunk.tsx
Labels: FE

#54 [Feat] add subject region CRUD
  server/src/main/java/com/codestates/connectInstructor/exception/ExceptionCode.java
  server/src/main/java/com/codestates/connectInstructor/region/controller/RegionController.java
  server/src/main/java/com/codestates/connectInstructor/region/dto/RegionDto.java
  server/src/main/java/com/codestates/connectInstructor/region/entity/Region.java
  server/src/main/java/com/codestates/connectInstructor/region/mapper/RegionMapper.java
  server/src/main/java/com/codestates/connectInstructor/region/repository/RegionRepository.java
  server/src/main/java/com/codestates/connectInstructor/region/service/RegionService.java
  server/src/main/java/com/codestates/connectInstructor/subject/controller/SubjectController.java
  server/src/main/java/com/codestates/connectInstructor/subject/dto/SubjectDto.java
  server/src/main/java/com/codestates/connectInstructor/subject/mapper/SubjectMapper.java
  server/src/main/java/com/codestates/connectInstructor/subject/repository/SubjectRepository.java
  server/src/main/java/com/codestates/connectInstructor/subject/service/SubjectService.java
Labels: BE

#56 Fe add private function
  client/data/data1.json
  client/src/components/Types/Types.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/pages/SignUp.tsx
  client/src/redux/slice/MemberSlice.tsx
  client/src/redux/store.tsx
Labels: FE

#59 Fe private page function
  client/data/data1.json
  client/src/components/Modal/ChangeModal.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/redux/slice/MemberSlice.tsx
Labels: FE

#61 Fe refactor
  client/src/Types/Types.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Footer/FooterGithub.tsx
  client/src/components/Footer/FooterIcon.tsx
  client/src/components/Menu/Search.tsx
  client/src/components/Menu/SearchForm.tsx
  client/src/components/Menu/SearchSelect.tsx
  client/src/components/Menu/SideList.tsx
  client/src/components/Menu/SideMembership.tsx
  client/src/components/Menu/Sidebar.tsx
  client/src/configs/Footer/configs.tsx
Labels: FE

#64 FEAT_Login_Alarm_Functio_Trim
  client/src/components/Loading/Loading.jsx
  client/src/pages/Login.tsx
  client/src/redux/slice/MemberSlice.tsx
Labels: FE

#66 [feat] 상태관리작업ing
  .DS_Store
  client/package.json
  client/src/Types/Types.tsx
  client/src/components/Profile/ProfileTab/Calendar.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Profile/ProfileTab/ScheduleList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/components/Schedule/Functions.tsx
  client/src/components/Schedule/SetSchedule.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/redux/slice/PofileSilce.tsx
  client/src/redux/slice/ScheduleSlice.tsx
  client/src/redux/store.tsx
  client/src/redux/thunk/Thunk.tsx
  data/data2.json
Labels: FE

#65 [Feat] add subject/region api documentation
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/codestates/connectInstructor/teacher/dto/TeacherDto.java
  server/src/main/java/com/codestates/connectInstructor/teacher/entity/Teacher.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/codestates/connectInstructor/region/RegionControllerTest.java
  server/src/test/java/com/codestates/connectInstructor/student/controller/StudentControllerTest.java
  server/src/test/java/com/codestates/connectInstructor/subject/SubjectControllerTest.java
  server/src/test/java/com/codestates/connectInstructor/teacher/controller/TeacherControllerTest.java
Labels: BE

#68 Fe private patch test
  client/src/components/Modal/AlertModal.tsx
  client/src/pages/Private.tsx
  data/data1.json
Labels: FE

#73 Fe modify detail page
  client/src/Types/Types.tsx
  client/src/components/DetailPage/RequestBtn.tsx
  client/src/components/DetailPage/TeacherInfo1.tsx
  client/src/components/DetailPage/TeacherInfo2.tsx
  client/src/components/ListPage/TeacherCard.tsx
  client/src/components/Menu/Search.tsx
  client/src/components/Menu/Sidebar.tsx
  client/src/components/Modal/ReqModal.tsx
  client/src/components/Modal/SInfoModal.tsx
  client/src/components/Modal/TInfoModal.tsx
  client/src/pages/DetailPage/DetailPage.tsx
  client/src/pages/ListPage/ListPage.tsx
  client/src/redux/slice/DetailPageSlice.tsx
  client/src/redux/slice/ListPageSlice.tsx
  client/src/redux/store.tsx
  client/src/redux/thunk/DetailPageThunk.tsx
  client/src/redux/thunk/ListPageThunk.tsx
  client/src/router/root.tsx
Labels: FE

#78 Fe social login
  client/src/components/Loading/Loading.tsx
  client/src/components/Modal/ChangeModal.tsx
  client/src/components/Modal/SocModal.tsx
  client/src/components/Modal/SocialModal.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/pages/SignUp.tsx
Labels: FE

#79 [Feat] add 강사 회원정보 하나씩 응답하는 거로 수정 + 해당 API문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/codestates/connectInstructor/teacher/controller/TeacherController.java
  server/src/main/java/com/codestates/connectInstructor/teacher/dto/TeacherDto.java
  server/src/main/java/com/codestates/connectInstructor/teacher/mapper/TeacherMapper.java
  server/src/main/java/com/codestates/connectInstructor/teacher/service/TeacherService.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/codestates/connectInstructor/teacher/controller/TeacherControllerTest.java
Labels: BE

#81 Fe private page thunk set
  client/src/components/Modal/ChangeModal.tsx
  client/src/components/Modal/SocModal.tsx
  client/src/components/Modal/SocialModal.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/pages/SignUp.tsx
  client/src/redux/slice/MemberSlice.tsx
Labels: FE

#82 Fe add schedule function
  client/src/Types/Types.tsx
  client/src/components/Profile/ProfileTab/ScheduleList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/components/Schedule/GetSchedule.tsx
  client/src/components/Schedule/SetSchedule.tsx
  client/src/pages/DetailPage/DetailPage.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/redux/slice/PofileSilce.tsx
  client/src/redux/slice/ScheduleSlice.tsx
  client/src/redux/thunk/Thunk.tsx
  data/data2.json
Labels: FE

#83 Fe modify design
  client/src/Types/Types.tsx
  client/src/components/DetailPage/RequestBtn.tsx
  client/src/components/DetailPage/TeacherInfo1.tsx
  client/src/components/DetailPage/TeacherInfo2.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Footer/FooterGithub.tsx
  client/src/components/Footer/FooterMember.tsx
  client/src/components/Header/Header.tsx
  client/src/components/ListPage/PageNumbers.tsx
  client/src/components/ListPage/TeacherCard.tsx
  client/src/components/Menu/Search.tsx
  client/src/components/Menu/SearchForm.tsx
  client/src/components/Menu/SearchSelect.tsx
  client/src/components/Menu/Sidebar.tsx
  client/src/components/Modal/ReqModal.tsx
  client/src/components/Modal/SInfoModal.tsx
  client/src/components/Modal/TInfoModal.tsx
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/components/Schedule/SetSchedule.tsx
  client/src/configs/Footer/configs.tsx
  client/src/index.css
  client/src/pages/DetailPage/DetailPage.tsx
  client/tailwind.config.js
Labels: FE

#80 [Feat] 강사검색 쿼리 수정. 강사정보는 강사본인만 수정 가능하게 하는거 일단 비활성화
  server/src/main/java/com/codestates/connectInstructor/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/codestates/connectInstructor/teacher/controller/TeacherController.java
  server/src/main/java/com/codestates/connectInstructor/teacher/dto/TeacherDto.java
  server/src/main/java/com/codestates/connectInstructor/teacher/mapper/TeacherMapper.java
  server/src/main/java/com/codestates/connectInstructor/teacher/repository/TeacherRepository.java
  server/src/main/java/com/codestates/connectInstructor/teacher/service/TeacherService.java
  server/src/test/java/com/codestates/connectInstructor/teacher/controller/TeacherControllerTest.java
Labels: BE

#89 Fe login auth
  .DS_Store
  client/src/components/Auth/CheckAuth.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/redux/slice/MemberSlice.tsx
  data/data1.json
Labels: FE

#93 Fe 로그인기능수정
  client/src/Types/Types.tsx
  client/src/components/Auth/GetAuth.tsx
  client/src/components/Modal/ChangeModal.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/redux/slice/MemberSlice.tsx
Labels: FE

#100 Fe modify list page pagination
  client/src/Types/Types.tsx
  client/src/components/DetailPage/TeacherInfo1.tsx
  client/src/components/DetailPage/TeacherInfo2.tsx
  client/src/components/ListPage/PageNumbers.tsx
  client/src/components/ListPage/Pagination.tsx
  client/src/components/ListPage/TeacherCard.tsx
  client/src/configs/List/config.tsx
  client/src/pages/DetailPage/DetailPage.tsx
  client/src/pages/ListPage/ListPage.tsx
  client/src/redux/slice/ListPageSlice.tsx
  client/src/redux/thunk/DetailPageThunk.tsx
  client/src/redux/thunk/ListPageThunk.tsx
Labels: FE

#96 Fe add profile function
  client/src/components/Items/EditandSave.tsx
  client/src/components/Items/OnlineDiv.tsx
  client/src/components/Modal/ConfirmModal.tsx
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/Option.tsx
  client/src/components/Profile/ProfileTab/OptionList.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Profile/ProfileTab/ScheduleList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/components/Schedule/GetSchedule.tsx
  client/src/components/Schedule/SetSchedule.tsx
  client/src/configs/Url/config.tsx
  client/src/hooks/UseCheckAuth.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/redux/slice/CategoriesSlice.tsx
  client/src/redux/slice/PofileSilce.tsx
  client/src/redux/slice/ProfileSilce.tsx
  client/src/redux/slice/TeacherSlice.tsx
  client/src/redux/store.tsx
  client/src/redux/thunk/Thunk.tsx
Labels: FE

#102 Fe add list/detail ap iapply
  client/package-lock.json
  client/package.json
  client/src/Types/Types.tsx
  client/src/components/DetailPage/RequestBtn.tsx
  client/src/components/DetailPage/TeacherInfo1.tsx
  client/src/components/DetailPage/TeacherInfo2.tsx
  client/src/pages/DetailPage/DetailPage.tsx
  client/src/redux/slice/DetailPageSlice.tsx
  client/src/redux/thunk/DetailPageThunk.tsx
Labels: FE

#103 FIX 로그인알람오류제거
  client/src/components/Auth/CheckAuth.tsx
  client/src/components/Auth/SetAuth.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/redux/slice/MemberSlice.tsx
  client/src/redux/slice/OauthSlice.tsx
  client/src/redux/store.tsx
Labels: help wanted, FE

#105 Fe add schedule function
  client/src/Types/Types.tsx
  client/src/components/Schedule/GetSchedule.tsx
  client/src/components/Schedule/MakeDateFunctions.tsx
  client/src/components/Schedule/SetSchedule.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/redux/slice/ScheduleSlice.tsx
  client/src/redux/thunk/Thunk.tsx
  data/data2.json
Labels: FE

#116 [feat] getschedule 수정
  client/src/components/Schedule/GetSchedule.tsx
Labels: FE

#118 FEAT_로그아웃기능구현
  client/src/components/Auth/Logout.tsx
  client/src/components/Auth/logoutUtils.tsx
  client/src/components/Modal/ChangeModal.tsx
  client/src/pages/Private.tsx
  client/src/redux/slice/MemberSlice.tsx
Labels: FE

#119 Feat_GNB_LogOut
  client/src/components/Menu/SideMembership.tsx
  client/src/pages/Login.tsx
Labels: FE

#124 [Feat] add security configuration( 손 볼 곳이 있음. 일단 작동엔 문제 없게 처리) 서버 재실행될 때 강사 2명 자동 등록.
  server/src/main/java/com/codestates/connectInstructor/security/config/SecurityConfiguration.java
  server/src/main/resources/db/h2/data.sql
  server/src/main/resources/static/docs/index.html
Labels: BE

#120 Fe add profile match function
  client/src/components/Modal/InfoModal.tsx
  client/src/redux/thunk/ProfilePageThunk.tsx
Labels: FE

#125 Fe add search ap iapply
  client/src/App.tsx
  client/src/Types/Types.tsx
  client/src/components/DetailPage/TeacherInfo1.tsx
  client/src/components/Menu/SearchForm.tsx
  client/src/components/Menu/SearchSelect.tsx
  client/src/components/Menu/Sidebar/Search.tsx
  client/src/components/Menu/Sidebar/SearchForm.tsx
  client/src/components/Menu/Sidebar/SearchSelect.tsx
  client/src/configs/Listpage/config.tsx
  client/src/pages/DetailPage/DetailPage.tsx
  client/src/pages/ListPage/ListPage.tsx
  client/src/redux/slice/ListPageSlice.tsx
  client/src/redux/slice/RegionsSlice.tsx
  client/src/redux/slice/SubjectSlice.tsx
  client/src/redux/store.tsx
  client/src/redux/thunk/ListPageThunk.tsx
  client/src/redux/thunk/SearchListThink.tsx
Labels: FE

#127 Fe refactor login
  .DS_Store
  client/src/components/Modal/ChangeModal.tsx
  client/src/components/Modal/ImageChangeModal.tsx
  client/src/pages/GetPassword.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/pages/SignUp.tsx
Labels: FE

#129 Fe getpassword
  client/src/components/Modal/ChangeModal.tsx
  client/src/components/Modal/SocialSignUpModal.tsx
  client/src/pages/GetPassword.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/pages/SignUp.tsx
Labels: FE

#133 Fe add request ap iapply
  client/src/App.tsx
  client/src/Types/Types.tsx
  client/src/components/DetailPage/RequestBtn.tsx
  client/src/components/DetailPage/TeacherInfo1.tsx
  client/src/components/Menu/Search/Search.tsx
  client/src/components/Menu/Search/SearchForm.tsx
  client/src/components/Menu/Search/SearchSelect.tsx
  client/src/components/Menu/Sidebar/SideList.tsx
  client/src/components/Menu/Sidebar/SideMembership.tsx
  client/src/components/Menu/Sidebar/Sidebar.tsx
  client/src/components/Modal/ReqModal/ReqForm.tsx
  client/src/components/Modal/ReqModal/ReqModal.tsx
  client/src/components/Modal/ReqModal/ReqSelect.tsx
  client/src/pages/DetailPage/DetailPage.tsx
  client/src/pages/ListPage/ListPage.tsx
  client/src/redux/slice/lessonRequestSlice.tsx
  client/src/redux/store.tsx
  client/src/redux/thunk/lessonRequestThunk.tsx
Labels: FE

#134 Fe modify profile
  client/src/components/Items/GetAccessToken.tsx
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Profile/ProfileTabs.tsx
  client/src/components/Schedule/SetSchedule.tsx
  client/src/configs/Url/config.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/redux/slice/ProfileSilce.tsx
  client/src/redux/slice/RequestSlice.tsx
  client/src/redux/thunk/ProfilePageThunk.tsx
  client/src/redux/thunk/RequestThunks.tsx
Labels: FE

#136 Refactor structure
  client/src/components/Auth/Logout.tsx
  client/src/components/Auth/SetAuth.tsx
  client/src/components/Modal/ChangeModal.tsx
  client/src/components/Modal/ImageChangeModal.tsx
  client/src/components/Modal/SocialSignUpModal.tsx
  client/src/pages/GetPassword.tsx
  client/src/pages/Login.tsx
  client/src/pages/Private.tsx
  client/src/pages/SignUp.tsx
  client/src/redux/slice/MemberSlice.tsx
Labels: FE

#139 BE_ h2 DB에서 MySQL DB로 전환
  server/src/main/resources/application.yml
Labels: BE

#142 FIX_Design Trim
  client/src/components/Modal/SocialSignUpModal.tsx
  client/src/pages/SignUp.tsx
Labels: FE

#144 [Fix] modify typeError modify
  client/src/components/Items/EditandSave.tsx
  client/src/components/Modal/InfoModal.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/OptionList.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Schedule/SetSchedule.tsx
  client/src/redux/slice/CategoriesSlice.tsx
  client/src/redux/slice/ProfileSilce.tsx
  client/src/redux/slice/TeacherSlice.tsx
  client/src/redux/slice/lessonRequestSlice.tsx
  client/src/redux/thunk/ProfilePageThunk.tsx
Labels: FE

#145 [Fix] ddl-auto: create
  server/src/main/resources/application.yml
Labels: BE

#146 [BE] 테이블의 option컬럼명은 mysql 예약어라서 options로 변경
  server/src/main/java/com/codestates/connectInstructor/student/entity/Student.java
  server/src/main/java/com/codestates/connectInstructor/teacher/entity/Teacher.java
Labels: BE

#147 BE_ddl-auto값을 none으로
  server/src/main/resources/application.yml
Labels: BE

#151 Fe modify modal
  client/src/components/Items/EditandSave.tsx
  client/src/components/Items/ModalPortal.tsx
  client/src/components/Items/ProtectedRoute.tsx
  client/src/components/Modal/AlertModal.tsx
  client/src/components/Modal/ImageChangeModal.tsx
  client/src/components/Modal/InfoModal.tsx
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileTab/Option.tsx
  client/src/components/Profile/ProfileTab/RequestList.tsx
  client/src/components/Schedule/SetSchedule.tsx
  client/src/components/Schedule/SortedTimeSlots.tsx
  client/src/pages/Profile/Profile.tsx
  client/src/redux/slice/ProfileSilce.tsx
  client/src/redux/slice/RequestSlice.tsx
  client/src/redux/slice/ScheduleSlice.tsx
  client/src/redux/store.tsx
  client/src/redux/thunk/ProfilePageThunk.tsx
  client/src/redux/thunk/RequestThunks.tsx
  client/src/router/root.tsx
Labels: FE

#162 BE_ 강사검색 쿼리 수정
  server/src/main/java/com/codestates/connectInstructor/teacher/repository/TeacherRepository.java
  server/src/main/java/com/codestates/connectInstructor/teacher/service/TeacherService.java
  server/src/main/resources/application.yml
Labels: BE

#170 [fix] 강사프로필 오류 수정
  client/src/components/Profile/ProfileDropdown.tsx
  client/src/components/Profile/ProfileHeader.tsx
  client/src/components/Profile/ProfileTab/Option.tsx
  client/src/components/Profile/ProfileTab/OptionList.tsx
  client/src/redux/thunk/ProfilePageThunk.tsx
Labels: FE

#171 Fe modify fixmodify
  client/src/Types/Types.tsx
  client/src/components/ListPage/TeacherCard.tsx
  client/src/components/Modal/ReqModal/ReqModal.tsx
  client/src/components/Modal/ReqModal/ReqScheduleList.tsx
  client/src/components/Modal/ReqModal/ReqSetSchedule.tsx
  client/src/pages/SignUp.tsx
  client/src/redux/slice/lessonRequestSlice.tsx
  client/src/redux/thunk/lessonRequestThunk.tsx
Labels: FE

#176 fixmodify
  client/src/components/ListPage/TeacherCard.tsx
Labels: FE
